repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-toml
      - id: end-of-file-fixer
      - id: flake8
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: [-l79,-S]
        language_version: python3.7
