name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Setup Python environment
        uses: actions/setup-python@v1.1.1
      - name: Install Poetry
        run: pip install --upgrade pip poetry
      - name: Install dependencies
        run: poetry install
      - name: Check Python style
        run: poetry run flake8 aurora_term/ tests/
      - name: Run tests
        run: poetry run pytest
